# Base mob components that originate from ES.
- type: entity
  id: ESBaseMob
  abstract: true
  components:
  - type: ESInherentLight
  - type: ESViewcone
  - type: ESViewconeOccludable
  - type: ESHoldToFace
  - type: KillTracker # used for masks
    killState: Dead
